name: 'summary_demo'
on:
  workflow_dispatch:
jobs:
  generate_outputs:
    name: Generate outputs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: ['job_1', 'job_2', 'job_3']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate output
        run: |
          echo "# ${{ matrix.job }}" >> $GITHUB_STEP_SUMMARY
          echo "'''bash" >> $GITHUB_STEP_SUMMARY
          echo "hello" >> $GITHUB_STEP_SUMMARY
          echo "'''" >> $GITHUB_STEP_SUMMARY
